/**
 * PROJECT:		Project Moonlight Kernel
 * FILE:		kernel/include/ke/exception.h
 * PURPOSE:		Exception support functions for the kernel
 * 
 * AUTHORS: 	Josh Theriault (joshriaul@gmail.com)
 * UPDATED:		1/05/2022
 */

#ifndef KERNEL_EXCEPTION_H
#define KERNEL_EXCEPTION_H

#include <api.h>

typedef enum _ke_exception_code
{
	EXCEPTION_DIVIDE_BY_ZERO,
	EXCEPTION_DEBUG_STEP,
	EXCEPTION_NMI,
	EXCEPTION_DEBUG_BREAK,
	EXCEPTION_INTEGER_OVERFLOW,
	EXCEPTION_BOUNDS_EXCEEDED,
	EXCEPTION_ILLEGAL_INSTRUCTION,
	EXCEPTION_DEVICE_UNAVAILABLE,
	EXCEPTION_UNHANDLED_FAULT,
	EXCEPTION_DEVICE_SEGMENT_OVERRUN,
	EXCEPTION_INVALID_TSS,
	EXCEPTION_SEGMENT_NOT_PRESET,
	EXCEPTION_STACK_FAULT,
	EXCEPTION_ACCESS_VIOLATION,
	EXCEPTION_PAGE_FAULT,
	EXCEPTION_FPU = 16,
	EXCEPTION_ALIGNMENT_CHECK,
	EXCEPTION_MACHINE_CHECK,
	EXCEPTION_SIMD,
	EXCEPTION_VIRTUALIZATION,
	EXCEPTION_CONTROL_PROTECTION,
	EXCEPTION_HYPERVISOR = 28,
	EXCEPTION_VMM_COMMUNICATION,
	EXCEPTION_SECURITY,
	EXCEPTION_RESERVED = 31
} KEXCEPTION_CODE;

#define KiExceptionCodeToCrashCode(e) (0xC00+(e))

#endif